config/routes.rb
Rails.application.routes.draw do
  root "diaries#index"

  resources :diaries do
    resources :notes
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/diary.rb
class Diary < ApplicationRecord
enum kind: {publlic:1, privatte:2}

has_many :notes, dependent: :destroy
validates :title, presence: true, length: { minimum: 1 }
validates :kind, presence: true
end

app/models/note.rb
class Note < ApplicationRecord
belongs_to :diary
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/diaries_controller.rb
class DiariesController < ApplicationController
http_basic_authenticate_with name: "dhh", password: "secret", except: [:index, :show]
  def index
    @diaries = Diary.all
  end
  def show
    @diary = Diary.find(params[:id])
  end
  def new
    @diary = Diary.new
  end

  def create
    @diary = Diary.new(title: "...", expiration: "...", kind: "...")

    if @diary.save
      redirect_to @diary
    else
      render :new
    end
  end
  def edit
    @article = Diary.find(params[:id])
  end

  def update
    @diary = Diary.find(params[:id])

    if @diary.update(diary_params)
      redirect_to @diary
    else
      render :edit
    end
  end
def destroy
    @diary = Diary.find(params[:id])
    @diary.destroy

    redirect_to root_path
  end

  private
    def diary_params
      params.require(:diary).permit(:title, :expiration, :kind)
    end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
http_basic_authenticate_with name: "dhh", password: "secret", only: :destroy
def create
    @diary = Diary.find(params[:diary_id])
    @note = @diary.notes.create(note_params)
    redirect_to diary_path(@diary)
  end
def destroy
    @article = Diary.find(params[:diary_id])
    @note = @diary.notes.find(params[:id])
    @note.destroy
    redirect_to diary_path(@diary)
  end
  private
    def note_params
      params.require(:note).permit(:text)
    end
end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/diaries_helper.rb
module DiariesHelper
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/diaries/edit.html.erb
<h1>Edit Diary</h1>

<%= render "form", diary: @diary %>

app/views/diaries/index.html.erb
<h1>Diaries</h1>

<ul>
  <% @diaries.each do |diary| %>
    <li>
      <%= link_to diary.title, diary %>
    </li>
  <% end %>
</ul>

<%= link_to "New Diary", new_diary_path %>

app/views/diaries/new.html.erb
<h1>New Diary</h1>

<%= form_with model: @diary, local: true do |form| %>
  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
    <%= @diary.errors.full_messages_for(:title).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :expiration %><br>
    <%= form.text_area :expiration %>
    <%= @diary.errors.full_messages_for(:expiration).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

<div>
    <%= form.label :kind %><br>
    <p><input type="radio" name="answer" value="privatte">Private<Br>
  <input type="radio" name="answer" value="publlic">Public<Br></p>
  <script>
  function kinddiary(f)
  {if (f.publlic.checked) f.text_area :expiration.disabled=1
  else f.text_area :expiration.disabled=0
  }</script>
     <%= @diary.errors.full_messages_for(:kind).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/diaries/show.html.erb
<h1><%= @diary.title %></h1>

<p><%= @diary.expiration %></p>

<p><%= @diary.kind %></p>

<ul>
  <li><%= link_to "Edit", edit_diary_path(@diary) %></li>
  <li><%= link_to "Destroy", diary_path(@diary),
                  method: :delete,
                  data: { confirm: "Are you sure?" } %></li>
</ul>
<h2>Notes</h2>
<%= render @diary.notes %>

<h2>Add a note:</h2>
<%= render 'notes/form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with model: [ @diary, @diary.notes.build ], local: true do |form| %>
  
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/notes/_note.html.erb
<p>
  <strong>Note:</strong>
  <%= note.text %>
</p>
<p>
  <%= link_to 'Destroy Note', [note.diary, note],
               method: :delete,
               data: { confirm: "Are you sure?" } %>
</p>